server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: app-crud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/ms-crud-v2?usesSL=false
    username: study
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver

